# Ruff configuration for Better Spotify Wrapped

# Target Python 3.10+
target-version = "py310"

# Maximum line length
line-length = 100

# Rules to enable
[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
]

ignore = [
    "E501",  # Line too long (handled by formatter)
    "B008",  # Do not perform function calls in argument defaults
]

# Allow autofix for all enabled rules
fixable = ["ALL"]

# Exclude common directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
]

[lint.per-file-ignores]
# Allow unused imports in __init__ files
"__init__.py" = ["F401"]
# Allow assert statements in tests
"tests/*" = ["B011"]

[lint.isort]
known-first-party = ["src", "dashboard"]

[format]
# Use double quotes for strings
quote-style = "double"

# Use Unix line endings
line-ending = "lf"

# Indent with spaces
indent-style = "space"

# Preserve quotes in docstrings
docstring-code-format = true